# output file : .index.mk
# output dir  : NHI1_HOME/theATL/tests
# created by  : NHI1_HOME/sbin/makefile_index.bash

TEST_FILES =               \
  aaa_exit.test            \
  appendComp.test          \
  append.test              \
  apply.test               \
  assemble.test            \
  assocd.test              \
  async.test               \
  atltest.test             \
  autoMkindex.test         \
  basic.test               \
  binary.test              \
  case.test                \
  chanio.test              \
  chan.test                \
  clock.test               \
  cmdAH.test               \
  cmdIL.test               \
  cmdInfo.test             \
  cmdMZ.test               \
  compExpr-old.test        \
  compExpr.test            \
  compile.test             \
  concat.test              \
  config.test              \
  coroutine.test           \
  dcall.test               \
  dict.test                \
  dstring.test             \
  encoding.test            \
  env.test                 \
  error.test               \
  eval.test                \
  event.test               \
  exec.test                \
  execute.test             \
  expr-old.test            \
  expr.test                \
  fCmd.test                \
  fileName.test            \
  fileSystemEncoding.test  \
  fileSystem.test          \
  foreach.test             \
  format.test              \
  for-old.test             \
  for.test                 \
  get.test                 \
  history.test             \
  if-old.test              \
  if.test                  \
  incr-old.test            \
  incr.test                \
  indexObj.test            \
  info.test                \
  init.test                \
  interp.test              \
  ioCmd.test               \
  iogt.test                \
  io.test                  \
  ioTrans.test             \
  join.test                \
  lindex.test              \
  link.test                \
  linsert.test             \
  listObj.test             \
  list.test                \
  llength.test             \
  lmap.test                \
  load.test                \
  lrange.test              \
  lrepeat.test             \
  lreplace.test            \
  lsearch.test             \
  lsetComp.test            \
  lset.test                \
  main.test                \
  mathop.test              \
  misc.test                \
  msgcat.test              \
  namespace-old.test       \
  namespace.test           \
  notify.test              \
  nre.test                 \
  obj.test                 \
  opt.test                 \
  package.test             \
  parseExpr.test           \
  parseOld.test            \
  parse.test               \
  pid.test                 \
  pkgMkIndex.test          \
  platform.test            \
  proc-old.test            \
  proc.test                \
  pwd.test                 \
  regexpComp.test          \
  regexp.test              \
  registry.test            \
  reg.test                 \
  rename.test              \
  resolver.test            \
  result.test              \
  safe.test                \
  scan.test                \
  security.test            \
  set-old.test             \
  set.test                 \
  socket.test              \
  source.test              \
  split.test               \
  stack.test               \
  stringComp.test          \
  stringObj.test           \
  string.test              \
  subst.test               \
  switch.test              \
  tailcall.test            \
  thread.test              \
  timer.test               \
  tm.test                  \
  trace.test               \
  unixFCmd.test            \
  unixFile.test            \
  unixForkEvent.test       \
  unixInit.test            \
  unixNotfy.test           \
  unknown.test             \
  unload.test              \
  uplevel.test             \
  upvar.test               \
  utf.test                 \
  util.test                \
  var.test                 \
  while-old.test           \
  while.test               

