DX_DIST = \
.labelignore \
.labeluse \
.make-ressources.bash \
.shortcut \
.vimrc \
Makefile.am \
Nhi1Docs.cfg \
docs.mk \
list.mk \
main/.labelignore \
main/.shortcut \
main/.vimrc \
main/Class.atl \
main/Doxyfile.main \
main/Initialize.atl \
main/Instance-Embedded.atl \
main/Instance-Global-namespace.atl \
main/Instance-Local-namespace.atl \
main/Instance-Super.atl \
main/Instance.atl \
main/Performance_libmyoo.atl \
main/Performance_tclmyoo.atl \
main/Performance_tcloo.atl \
main/libmyoox.doc \
main/main.config \
main/main.doc \
main/myoo.doc \
main/performance-test-my-variation.atl \
main/performance-test-my-variation.doc \
main/tclmyoo.doc \
package.config \
pics/tcloo_versa_myoo.png \
ressources.make \
theLib.bash \
theLib.css \
.make_filelist_for_makefile_from_git.bash
